In [1]:
print("test")

test

In [ ]:
### 형사 판례 목록 긁기 테스트
import requests
import pandas as pd

OC = "sdunge"  #인증키

# 판례 목록조회 API
url = "https://www.law.go.kr/DRF/lawSearch.do"
params = {
    "OC": OC,
    "target": "prec",      # 판례
    "type": "JSON",
    "query": "사기",        # 검색 키워드 (형사 죄명)
    "display": 20,         # 한 페이지에 20건
    "page": 1
}

res = requests.get(url, params=params)
data = res.json()

# 결과 확인
prec_list = data["PrecSearch"]["prec"]
print(f"받아온 판례 수: {len(prec_list)}건")
print(f"전체 검색 건수: {data['PrecSearch']['totalCnt']}건")

# 표로 보기
df = pd.DataFrame(prec_list)
df.head()

받아온 판례 수: 20건
전체 검색 건수: 2828건

,id,사건번호,데이터출처명,사건종류코드,사건종류명,선고,선고일자,판례일련번호,판결유형,법원종류코드,법원명,판례상세링크,사건명
0,1,전주지방법원-2025-구합-1210,국세법령정보시스템,400107,일반행정,,2026.08.13,623771,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,다단계 폰지사기 투자자가 수령한 수익금은 비영업대금의 이익으로서 이자소득에 해당함
1,2,서울행정법원-2025-구합-54286,국세법령정보시스템,400107,일반행정,,2026.06.12,622179,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,과세전적부심사 기회 박탈의 절차적 하자 여부
2,3,인천지방법원-2025-구단-50440,국세법령정보시스템,400107,일반행정,,2026.06.02,621329,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,세무사의 사기 행위 및 기한 후 신고결정이 3개월이 지났다는 사유는 가산세의 감면 ...
3,4,서울중앙지방법원-2025-가단-90444,국세법령정보시스템,400101,민사,,2026.05.11,622175,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,매매예약완결권은 일종의 형성권으로서 당사자 사이에 그 행사기간을 약정한 때에는 그 ...
4,5,2025도10476,대법원,400102,형사,선고,2026.05.08,621903,판결,,대법원,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,사기[검사가 양형에 관한 의견을 법정에서 진술하지 않고 변론종결 후 서면으로 제출한...

### CSV 파일 변환

In [4]:
import time

OC = "sdunge"
url = "https://www.law.go.kr/DRF/lawSearch.do"

all_precs = []
keyword = "사기"       
max_pages = 20          

for page in range(1, max_pages + 1):
    params = {
        "OC": OC, "target": "prec", "type": "JSON",
        "query": keyword, "display": 20, "page": page
    }
    res = requests.get(url, params=params)
    data = res.json()
    precs = data["PrecSearch"].get("prec", [])
    if not precs:          # 더 이상 없으면 중단
        break
    all_precs.extend(precs)
    print(f"{page}페이지 완료 — 누적 {len(all_precs)}건")
    time.sleep(0.3)        # API 부담 안 주게 잠깐 쉬기

# 표로 정리
df = pd.DataFrame(all_precs)
print(f"\n총 {len(df)}건 수집 완료")
df.head()

1페이지 완료 — 누적 20건
2페이지 완료 — 누적 40건
3페이지 완료 — 누적 60건
4페이지 완료 — 누적 80건
5페이지 완료 — 누적 100건
6페이지 완료 — 누적 120건
7페이지 완료 — 누적 140건
8페이지 완료 — 누적 160건
9페이지 완료 — 누적 180건
10페이지 완료 — 누적 200건
11페이지 완료 — 누적 220건
12페이지 완료 — 누적 240건
13페이지 완료 — 누적 260건
14페이지 완료 — 누적 280건
15페이지 완료 — 누적 300건
16페이지 완료 — 누적 320건
17페이지 완료 — 누적 340건
18페이지 완료 — 누적 360건
19페이지 완료 — 누적 380건
20페이지 완료 — 누적 400건

총 400건 수집 완료

,id,사건번호,데이터출처명,사건종류코드,사건종류명,선고,선고일자,판례일련번호,판결유형,법원종류코드,법원명,판례상세링크,사건명
0,1,전주지방법원-2025-구합-1210,국세법령정보시스템,400107,일반행정,,2026.08.13,623771,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,다단계 폰지사기 투자자가 수령한 수익금은 비영업대금의 이익으로서 이자소득에 해당함
1,2,서울행정법원-2025-구합-54286,국세법령정보시스템,400107,일반행정,,2026.06.12,622179,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,과세전적부심사 기회 박탈의 절차적 하자 여부
2,3,인천지방법원-2025-구단-50440,국세법령정보시스템,400107,일반행정,,2026.06.02,621329,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,세무사의 사기 행위 및 기한 후 신고결정이 3개월이 지났다는 사유는 가산세의 감면 ...
3,4,서울중앙지방법원-2025-가단-90444,국세법령정보시스템,400101,민사,,2026.05.11,622175,,,,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,매매예약완결권은 일종의 형성권으로서 당사자 사이에 그 행사기간을 약정한 때에는 그 ...
4,5,2025도10476,대법원,400102,형사,선고,2026.05.08,621903,판결,,대법원,/DRF/lawService.do?OC=sdunge&target=prec&ID=62...,사기[검사가 양형에 관한 의견을 법정에서 진술하지 않고 변론종결 후 서면으로 제출한...

In [6]:
# raw 폴더에 csv파일 저장
save_path = "prec_fraud.csv"
df.to_csv(save_path, index=False, encoding="utf-8-sig")

print(f"저장 완료: {save_path}")
print(f"저장된 판례 수: {len(df)}건")

저장 완료: prec_fraud.csv
저장된 판례 수: 400건

In [8]:
print(f"전체 판례: {len(df)}건")

전체 판례: 400건

### 본문 테스트

In [18]:
from elasticsearch import Elasticsearch, helpers
import pandas as pd

# 연결
es = Elasticsearch("http://localhost:9200")
print("연결 확인:", es.info()["version"]["number"])

# CSV 읽기 (노트북이 raw 폴더에 있으니 파일명만)
df = pd.read_csv("prec_fraud.csv")
print(f"판례 {len(df)}건 로드")

# 인덱스 이름
INDEX = "prec_search"

# 기존 인덱스 있으면 삭제하고 새로 (재실행 대비)
if es.indices.exists(index=INDEX):
    es.indices.delete(index=INDEX)
es.indices.create(index=INDEX)

# 판례를 하나씩 색인 (사건명 위주)
actions = []
for i, row in df.iterrows():
    actions.append({
        "_index": INDEX,
        "_id": i,
        "_source": {
            "사건명": str(row.get("사건명", "")),
            "사건번호": str(row.get("사건번호", "")),
            "선고일자": str(row.get("선고일자", "")),
            "판례일련번호": str(row.get("판례일련번호", "")),
        }
    })

helpers.bulk(es, actions)
es.indices.refresh(index=INDEX)
print(f"색인 완료: {es.count(index=INDEX)['count']}건")

연결 확인: 9.1.0
판례 400건 로드
색인 완료: 400건

In [19]:
# 실제 컬럼 확인
print(df.columns.tolist())
print()
# 각 필드 예시값 하나씩
print(df.iloc[0])

['id', '사건번호', '데이터출처명', '사건종류코드', '사건종류명', '선고', '선고일자', '판례일련번호', '판결유형', '법원종류코드', '법원명', '판례상세링크', '사건명']

id                                                        1
사건번호                                    전주지방법원-2025-구합-1210
데이터출처명                                            국세법령정보시스템
사건종류코드                                               400107
사건종류명                                                  일반행정
선고                                                      NaN
선고일자                                             2026.08.13
판례일련번호                                               623771
판결유형                                                    NaN
법원종류코드                                                  NaN
법원명                                                     NaN
판례상세링크    /DRF/lawService.do?OC=sdunge&target=prec&ID=62...
사건명           다단계 폰지사기 투자자가 수령한 수익금은 비영업대금의 이익으로서 이자소득에 해당함
Name: 0, dtype: object

In [21]:
def search(keyword, size=5):
    res = es.search(index="prec_search", query={"match": {"사건명": keyword}}, size=size)
    print(f"\n'{keyword}' → {res['hits']['total']['value']}건")
    for hit in res["hits"]["hits"]:
        print(f"  [{hit['_score']:.2f}] {hit['_source']['사건명'][:50]}")

search("사기")
search("기망")
search("속여")

'사기' → 149건
  [1.60] 특정경제범죄가중처벌등에관한법률위반(사기)·사기
  [1.60] 특정경제범죄가중처벌등에관한법률위반(사기)·사기
  [1.60] 특정경제범죄가중처벌등에관한법률위반(사기)·사기
  [1.60] 의료법위반·특정경제범죄가중처벌등에관한법률위반(사기)·사기
  [1.60] 특정경제범죄가중처벌등에관한법률위반(사기)·사기

'기망' → 0건

'속여' → 0건

In [25]:
# 본문 검색 옵션 추가해서 목록
params = {
    "OC": "sdunge", "target": "prec", "type": "JSON",
    "query": "사기", "display": 20, "page": 1,
    "search": 2,                    # 판시사항+본문까지 검색
    "prncYd": "20200101~20241231"   # 최근 5년 (대법원/법원 판례 위주)
}
res = requests.get("https://www.law.go.kr/DRF/lawSearch.do", params=params)
data = res.json()
precs = data["PrecSearch"]["prec"]

# 출처 확인 
for p in precs[:5]:
    print(f"{p['데이터출처명']} | {p['법원명']} | {p['사건명'][:30]}")

대법원 | 수원지방법원 | 사기
대법원 | 서울중앙지방법원 | 수사기관의압수에관한처분취소·변경
국세법령정보시스템 |  | 과세요건 사실의 존재에 대한 증명책임
대법원 | 창원지방법원 | 사기·특정범죄가중처벌등에관한법률위반(위험운전치사상)·도
대법원 | 대법원 | 수사기관압수처분에대한재항고[경찰공무원 외에 생명보험협회

In [26]:
sample_id = precs[0]["판례일련번호"]
p = {"OC": "sdunge", "target": "prec", "ID": sample_id, "type": "JSON"}
r = requests.get("https://www.law.go.kr/DRF/lawService.do", params=p)
d = r.json()
print(list(d["Law"].keys()) if "Law" in d else r.text[:200])

{"PrecService": {
    "판시사항": "",
    "참조판례": "",
    "사건종류명": "형사",
    "판결요지": "",
    "참조조문": "",
    "선고일자": "20241227",
    "법원명": "수원지방법원",
    "사건명": "사기",
    "판례내용": "【피 고 인】 피고인<br/>【항 소 인】

In [27]:
import time

OC = "sdunge"
search_url = "https://www.law.go.kr/DRF/lawSearch.do"
detail_url = "https://www.law.go.kr/DRF/lawService.do"

# 1. 형사 판례 목록 
all_precs = []
for page in range(1, 11):   # 10페이지 = 약 200건
    params = {
        "OC": OC, "target": "prec", "type": "JSON",
        "query": "사기", "display": 20, "page": page,
        "search": 2, "prncYd": "20200101~20241231"
    }
    r = requests.get(search_url, params=params)
    precs = r.json()["PrecSearch"].get("prec", [])
    if not precs:
        break
    all_precs.extend(precs)
    print(f"{page}페이지 — 누적 {len(all_precs)}건")
    time.sleep(0.3)

print(f"\n목록 {len(all_precs)}건 수집\n")

# 2. 각 판례의 본문 긁기 (형사만)
results = []
for i, p in enumerate(all_precs):
    sid = p["판례일련번호"]
    r = requests.get(detail_url, params={"OC":OC,"target":"prec","ID":sid,"type":"JSON"})
    d = r.json()

    # 본문이 정상이고 형사인 것만
    if "PrecService" in d and isinstance(d["PrecService"], dict):
        svc = d["PrecService"]
        if svc.get("사건종류명") == "형사" and svc.get("판례내용"):
            results.append({
                "판례일련번호": sid,
                "사건명": svc.get("사건명",""),
                "법원명": svc.get("법원명",""),
                "선고일자": svc.get("선고일자",""),
                "판시사항": svc.get("판시사항",""),
                "판결요지": svc.get("판결요지",""),
                "참조조문": svc.get("참조조문",""),
                "참조판례": svc.get("참조판례",""),
                "판례내용": svc.get("판례내용",""),
            })
    if (i+1) % 20 == 0:
        print(f"본문 {i+1}건 처리 — 형사 확보 {len(results)}건")
    time.sleep(0.3)

print(f"\n최종 형사 판례(본문 포함): {len(results)}건")

df_body = pd.DataFrame(results)
df_body.head()

1페이지 — 누적 20건
2페이지 — 누적 40건
3페이지 — 누적 60건
4페이지 — 누적 80건
5페이지 — 누적 100건
6페이지 — 누적 120건
7페이지 — 누적 140건
8페이지 — 누적 160건
9페이지 — 누적 180건
10페이지 — 누적 200건

목록 200건 수집

본문 20건 처리 — 형사 확보 10건
본문 40건 처리 — 형사 확보 19건
본문 60건 처리 — 형사 확보 25건
본문 80건 처리 — 형사 확보 32건
본문 100건 처리 — 형사 확보 40건
본문 120건 처리 — 형사 확보 50건
본문 140건 처리 — 형사 확보 56건
본문 160건 처리 — 형사 확보 62건
본문 180건 처리 — 형사 확보 65건
본문 200건 처리 — 형사 확보 73건

최종 형사 판례(본문 포함): 73건

,판례일련번호,사건명,법원명,선고일자,판시사항,판결요지,참조조문,참조판례,판례내용
0,606037,사기,수원지방법원,20241227,,,,,【피 고 인】 피고인<br/>【항 소 인】 피고인(원심판결들에 대하여) 및 검사(제...
1,615847,수사기관의압수에관한처분취소·변경,서울중앙지방법원,20241220,,,,,【준항고인】 준항고인 <br/>【대 ...
2,607233,사기·특정범죄가중처벌등에관한법률위반(위험운전치사상)·도로교통법위반·범죄수익은닉의규제...,창원지방법원,20241219,,,,,【피 고 인】 피고인 1 외 4인<br/>【항 소 인】 쌍방<br/>【검 사】...
3,600509,수사기관압수처분에대한재항고[경찰공무원 외에 생명보험협회 소속 치과위생사가 집행에 참...,대법원,20241216,수사기관이 압수·수색 현장에 형사소송법상 참여권자나 참여할 수 있도록 규정된 사람...,압수·수색영장은 검사의 지휘에 의하여 사법경찰관리가 집행하고(형사소송법 제115조...,"헌법 제12조 제1항, 제16조, 제17조, 형사소송법 제115조 제1항, 제119...",,【재항고인】 재항고인<br/>【변 호 인】 법무법인(유한) 태평양 담당변호사 이진한...
4,612059,사기,대법원,20241212,<br/> 전화 등 전기통신수단을 이용한 금융사기 조직범죄(보이스피싱)에서 현금수거...,,"형법 제13조, 제30조, 제347조, 형사소송법 제308조 <br/>","대법원 1997. 9. 12. 선고 97도1706 판결(공1997하, 3215),...",【피 고 인】 피고인 <br/>【상 ...

In [28]:
df_body

,판례일련번호,사건명,법원명,선고일자,판시사항,판결요지,참조조문,참조판례,판례내용
0,606037,사기,수원지방법원,20241227,,,,,【피 고 인】 피고인<br/>【항 소 인】 피고인(원심판결들에 대하여) 및 검사(제...
1,615847,수사기관의압수에관한처분취소·변경,서울중앙지방법원,20241220,,,,,【준항고인】 준항고인 <br/>【대 ...
2,607233,사기·특정범죄가중처벌등에관한법률위반(위험운전치사상)·도로교통법위반·범죄수익은닉의규제...,창원지방법원,20241219,,,,,【피 고 인】 피고인 1 외 4인<br/>【항 소 인】 쌍방<br/>【검 사】...
3,600509,수사기관압수처분에대한재항고[경찰공무원 외에 생명보험협회 소속 치과위생사가 집행에 참...,대법원,20241216,수사기관이 압수·수색 현장에 형사소송법상 참여권자나 참여할 수 있도록 규정된 사람...,압수·수색영장은 검사의 지휘에 의하여 사법경찰관리가 집행하고(형사소송법 제115조...,"헌법 제12조 제1항, 제16조, 제17조, 형사소송법 제115조 제1항, 제119...",,【재항고인】 재항고인<br/>【변 호 인】 법무법인(유한) 태평양 담당변호사 이진한...
4,612059,사기,대법원,20241212,<br/> 전화 등 전기통신수단을 이용한 금융사기 조직범죄(보이스피싱)에서 현금수거...,,"형법 제13조, 제30조, 제347조, 형사소송법 제308조 <br/>","대법원 1997. 9. 12. 선고 97도1706 판결(공1997하, 3215),...",【피 고 인】 피고인 <br/>【상 ...
...,...,...,...,...,...,...,...,...,...
68,238637,업무방해·전자금융거래법위반,대법원,20230831,<br/> [1] 계좌개설 신청인이 접근매체를 양도할 의사로 금융기관에 법인 명의...,<br/> [1] 상대방으로부터 신청을 받아 일정한 자격요건 등을 갖춘 경우에 한...,[1] 형법 제314조 제1항 / [2] 구 전자금융거래법(2015. 1. 20....,"[1] 대법원 2004. 3. 26. 선고 2003도7927 판결(공2004상, ...",【피 고 인】 피고인 <br/>【상 ...
69,607193,사기,대구지방법원 김천지원,20230830,,,,,"【피 고 인】 피고인<br/>【검 사】 배성재(기소), 공도운(공판)<br/>..."
70,238809,특정경제범죄가중처벌등에관한법률위반(사기)·사기,대전고등법원,20230825,,,,,"【피 고 인】 피고인<br/>【항 소 인】 쌍방<br/>【검 사】 정우석, 탁..."
71,614417,뇌물수수·뇌물공여·사기,부산고등법원(울산),20230810,,,,,【피 고 인】 피고인 5 외 5인<br/>【항 소 인】 ...
72,239957,사기·자동차관리법위반,서울북부지방법원,20230720,,,,,"【피 고 인】 피고인 1 외 1인<br/>【검 사】 정하은, 김용선(기소), ..."